# Generated by Django 5.1.3 on 2024-11-11 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hirdetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cim', models.CharField(max_length=255)),
                ('leiras', models.TextField()),
                ('ar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kep', models.ImageField(upload_to='kepek/')),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('felhasznalo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kedveles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kedvelt', models.BooleanField(default=False)),
                ('felhasznalo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hirdetes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingatlan.hirdetes')),
            ],
        ),
    ]
